FROM n8nio/n8n:1.109.2

# Diretório para nodes customizados
RUN mkdir -p /home/node/.n8n/nodes
WORKDIR /home/node/.n8n/nodes

ARG PGHOST PGPORT PGDATABASE PGUSER PGPASSWORD
ENV DB_TYPE=postgresdb
ENV DB_POSTGRESDB_DATABASE=$PGDATABASE
ENV DB_POSTGRESDB_HOST=$PGHOST
ENV DB_POSTGRESDB_PORT=$PGPORT
ENV DB_POSTGRESDB_USER=$PGUSER
ENV DB_POSTGRESDB_PASSWORD=$PGPASSWORD

ARG REDISHOST REDISPORT REDISUSER REDISPASSWORD
ENV QUEUE_BULL_REDIS_HOST=$REDISHOST
ENV QUEUE_BULL_REDIS_PORT=$REDISPORT
ENV QUEUE_BULL_REDIS_USERNAME=$REDISUSER
ENV QUEUE_BULL_REDIS_PASSWORD=$REDISPASSWORD
ENV QUEUE_BULL_REDIS_DB=0

ENV EXECUTIONS_MODE=queue
ENV EXECUTIONS_PROCESS=main
ENV OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=true
ENV N8N_ENCRYPTION_KEY=$ENCRYPTION_KEY
ENV GENERIC_TIMEZONE=America/Sao_Paulo
ENV PORT=5678

CMD ["n8n", "start", "--port", "5678"]
