FROM n8nio/n8n:1.109.2

RUN mkdir -p /home/node/.n8n/nodes
WORKDIR /home/node/.n8n/nodes

ARG PGPASSWORD
ARG PGHOST
ARG PGPORT
ARG PGDATABASE
ARG PGUSER
ARG ENCRYPTION_KEY

ENV DB_TYPE=postgresdb
ENV DB_POSTGRESDB_DATABASE=$PGDATABASE
ENV DB_POSTGRESDB_HOST=$PGHOST
ENV DB_POSTGRESDB_PORT=$PGPORT
ENV DB_POSTGRESDB_USER=$PGUSER
ENV DB_POSTGRESDB_PASSWORD=$PGPASSWORD
ENV N8N_ENCRYPTION_KEY=$ENCRYPTION_KEY
ENV N8N_HOST=0.0.0.0
ENV PORT=5678
ENV N8N_WAIT_FOR_DB=true
ENV N8N_WAIT_FOR_REDIS=true

CMD ["n8n", "start", "--host", "0.0.0.0"]
